### ISSUE TITLE
memory leaks in debuginfod

### ISSUE THREAD

**Issue by evverx** [evverx/elfutils#21]
```
2021-12-05T03:46:03.4091534Z =================================================================
2021-12-05T03:46:03.4092091Z ==23772==ERROR: LeakSanitizer: detected memory leaks
2021-12-05T03:46:03.4092507Z
2021-12-05T03:46:03.4092974Z Direct leak of 128 byte(s) in 2 object(s) allocated from:
2021-12-05T03:46:03.4093838Z     #0 0x49aa62 in calloc (/home/runner/work/elfutils/elfutils/debuginfod/debuginfod+0x49aa62)
2021-12-05T03:46:03.4095228Z     #1 0x7ffbe825b789 in debuginfod_begin /home/runner/work/elfutils/elfutils/debuginfod/debuginfod-client.c:1445:12
2021-12-05T03:46:03.4096409Z     #2 0x4cdb62 in debuginfod_pool_begin() /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:1820:10
2021-12-05T03:46:03.4098291Z     #3 0x4e2106 in handle_buildid(MHD_Connection*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*) /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:1946:31
2021-12-05T03:46:03.4100328Z     #4 0x4d8581 in handler_cb(void*, MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*, void**) /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:2289:15
2021-12-05T03:46:03.4101704Z     #5 0x7ffbe82217e0  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x67e0)
2021-12-05T03:46:03.4102199Z
```

**Comment by evverx** [comment]
This should be fixed in https://sourceware.org/pipermail/elfutils-devel/2021q4/004425.html
