### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow: sqlite3_sharedprefix_fn

### ISSUE THREAD

**Issue by evverx** [evverx/elfutils#8]
```
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
...
2021-12-02T14:05:04.7190730Z FAIL: run-debuginfod-archive-groom.sh
2021-12-02T14:05:11.5083450Z FAIL: run-debuginfod-archive-rename.sh
2021-12-02T14:05:14.4321829Z FAIL: run-debuginfod-archive-test.sh
...
2021-12-02T14:05:39.8786869Z 
2021-12-02T14:05:39.8787940Z FAIL: run-debuginfod-archive-groom.sh
2021-12-02T14:05:39.8788725Z =====================================
2021-12-02T14:05:39.8789070Z 
...
2021-12-02T14:05:40.0203779Z =================================================================
2021-12-02T14:05:40.0205021Z ==27180==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c0000357c0 at pc 0x5645a07c54dd bp 0x7f2fed778ae0 sp 0x7f2fed778ad0
2021-12-02T14:05:40.0206243Z READ of size 1 at 0x60c0000357c0 thread T37 (mhd-buildid)
2021-12-02T14:05:40.0207209Z     #0 0x5645a07c54dc in sqlite3_sharedprefix_fn /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:3707
2021-12-02T14:05:40.0208474Z     #1 0x7f2ff7326d45  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x9bd45)
2021-12-02T14:05:40.0209622Z     #2 0x7f2ff7330419 in sqlite3_step (/lib/x86_64-linux-gnu/libsqlite3.so.0+0xa5419)
2021-12-02T14:05:40.0211202Z     #3 0x5645a08c3f34 in sqlite_ps::step() /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:977
2021-12-02T14:05:40.0212321Z     #4 0x5645a07f7da3 in handle_buildid /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:1916
2021-12-02T14:05:40.0213534Z     #5 0x5645a0825298 in handler_cb /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:2286
2021-12-02T14:05:40.0214911Z     #6 0x7f2ff73bc7e0  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x67e0)
2021-12-02T14:05:40.0216117Z     #7 0x7f2ff73be837  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x8837)
2021-12-02T14:05:40.0217315Z     #8 0x7f2ff73c08dd  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0xa8dd)
2021-12-02T14:05:40.0218497Z     #9 0x7f2ff73c4068  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0xe068)
2021-12-02T14:05:40.0219748Z     #10 0x7f2ff71af608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
2021-12-02T14:05:40.0220883Z     #11 0x7f2ff656a292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
2021-12-02T14:05:40.0221367Z 
2021-12-02T14:05:40.0222196Z 0x60c0000357c0 is located 0 bytes to the right of 128-byte region [0x60c000035740,0x60c0000357c0)
2021-12-02T14:05:40.0223131Z allocated by thread T37 (mhd-buildid) here:
2021-12-02T14:05:40.0224142Z     #0 0x7f2ff7edebc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
2021-12-02T14:05:40.0225271Z     #1 0x7f2ff72d0cfa  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x45cfa)
2021-12-02T14:05:40.0225791Z 
2021-12-02T14:05:40.0226501Z Thread T37 (mhd-buildid) created by T1 (MHD-listen) here:
2021-12-02T14:05:40.0227589Z     #0 0x7f2ff7e0b805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
2021-12-02T14:05:40.0228808Z     #1 0x7f2ff73ca9ee  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x149ee)
2021-12-02T14:05:40.0229388Z 
2021-12-02T14:05:40.0230030Z Thread T1 (MHD-listen) created by T0 here:
2021-12-02T14:05:40.0231043Z     #0 0x7f2ff7e0b805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
2021-12-02T14:05:40.0232881Z     #1 0x7f2ff73ca9ee  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x149ee)
2021-12-02T14:05:40.0233477Z 
2021-12-02T14:05:40.0234895Z SUMMARY: AddressSanitizer: heap-buffer-overflow /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:3707 in sqlite3_sharedprefix_fn
2021-12-02T14:05:40.0236080Z Shadow bytes around the buggy address:
2021-12-02T14:05:40.0236714Z   0x0c187fffeaa0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
2021-12-02T14:05:40.0237355Z   0x0c187fffeab0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
2021-12-02T14:05:40.0238034Z   0x0c187fffeac0: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.0238634Z   0x0c187fffead0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.0239173Z   0x0c187fffeae0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.0239769Z =>0x0c187fffeaf0: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
2021-12-02T14:05:40.0240310Z   0x0c187fffeb00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.0240893Z   0x0c187fffeb10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.0241524Z   0x0c187fffeb20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.0242169Z   0x0c187fffeb30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.0242972Z   0x0c187fffeb40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.0243732Z Shadow byte legend (one shadow byte represents 8 application bytes):
2021-12-02T14:05:40.0244476Z   Addressable:           00
2021-12-02T14:05:40.0245065Z   Partially addressable: 01 02 03 04 05 06 07 
2021-12-02T14:05:40.0245618Z   Heap left redzone:       fa
2021-12-02T14:05:40.0246122Z   Freed heap region:       fd
2021-12-02T14:05:40.0246609Z   Stack left redzone:      f1
2021-12-02T14:05:40.0247095Z   Stack mid redzone:       f2
2021-12-02T14:05:40.0247592Z   Stack right redzone:     f3
2021-12-02T14:05:40.0248108Z   Stack after return:      f5
2021-12-02T14:05:40.0248579Z   Stack use after scope:   f8
2021-12-02T14:05:40.0249069Z   Global redzone:          f9
2021-12-02T14:05:40.0249545Z   Global init order:       f6
2021-12-02T14:05:40.0250007Z   Poisoned by user:        f7
2021-12-02T14:05:40.0250506Z   Container overflow:      fc
2021-12-02T14:05:40.0251160Z   Array cookie:            ac
2021-12-02T14:05:40.0251650Z   Intra object redzone:    bb
2021-12-02T14:05:40.0252123Z   ASan internal:           fe
2021-12-02T14:05:40.0252602Z   Left alloca redzone:     ca
2021-12-02T14:05:40.0253101Z   Right alloca redzone:    cb
2021-12-02T14:05:40.0253552Z   Shadow gap:              cc
2021-12-02T14:05:40.0254259Z ==27180==ABORTING'
```
```
2021-12-02T14:05:40.0279309Z 
2021-12-02T14:05:40.0280226Z FAIL: run-debuginfod-archive-rename.sh
2021-12-02T14:05:40.0281025Z ======================================
2021-12-02T14:05:40.0281281Z 
...
2021-12-02T14:05:40.1598603Z [Thu Dec  2 14:05:11 2021] (27529/27725): searching for buildid=bc1febfd03ca05e030f0d205f7659db29f8a4b30 artifacttype=source suffix=/usr/src/debug/hello-1.0/hello.c
2021-12-02T14:05:40.1599672Z =================================================================
2021-12-02T14:05:40.1600902Z ==27529==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c00003c3c0 at pc 0x55bdd5fdf4dd bp 0x7f1c67397ae0 sp 0x7f1c67397ad0
2021-12-02T14:05:40.1602128Z READ of size 1 at 0x60c00003c3c0 thread T37 (mhd-buildid)
2021-12-02T14:05:40.1603116Z     #0 0x55bdd5fdf4dc in sqlite3_sharedprefix_fn /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:3707
2021-12-02T14:05:40.1604577Z     #1 0x7f1c70f45d45  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x9bd45)
2021-12-02T14:05:40.1605742Z     #2 0x7f1c70f4f419 in sqlite3_step (/lib/x86_64-linux-gnu/libsqlite3.so.0+0xa5419)
2021-12-02T14:05:40.1606979Z     #3 0x55bdd60ddf34 in sqlite_ps::step() /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:977
2021-12-02T14:05:40.1608115Z     #4 0x55bdd6011da3 in handle_buildid /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:1916
2021-12-02T14:05:40.1609228Z     #5 0x55bdd603f298 in handler_cb /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:2286
2021-12-02T14:05:40.1610503Z     #6 0x7f1c70fdb7e0  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x67e0)
2021-12-02T14:05:40.1611801Z     #7 0x7f1c70fdd837  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x8837)
2021-12-02T14:05:40.1612994Z     #8 0x7f1c70fdf8dd  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0xa8dd)
2021-12-02T14:05:40.1614192Z     #9 0x7f1c70fe3068  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0xe068)
2021-12-02T14:05:40.1615413Z     #10 0x7f1c70dce608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
2021-12-02T14:05:40.1616541Z     #11 0x7f1c70189292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
2021-12-02T14:05:40.1617013Z 
2021-12-02T14:05:40.1617865Z 0x60c00003c3c0 is located 0 bytes to the right of 128-byte region [0x60c00003c340,0x60c00003c3c0)
2021-12-02T14:05:40.1618824Z allocated by thread T37 (mhd-buildid) here:
2021-12-02T14:05:40.1619807Z     #0 0x7f1c71afdbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
2021-12-02T14:05:40.1620913Z     #1 0x7f1c70eefcfa  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x45cfa)
2021-12-02T14:05:40.1621433Z 
2021-12-02T14:05:40.1622144Z Thread T37 (mhd-buildid) created by T1 (MHD-listen) here:
2021-12-02T14:05:40.1623225Z     #0 0x7f1c71a2a805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
2021-12-02T14:05:40.1624435Z     #1 0x7f1c70fe99ee  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x149ee)
2021-12-02T14:05:40.1625005Z 
2021-12-02T14:05:40.1625642Z Thread T1 (MHD-listen) created by T0 here:
2021-12-02T14:05:40.1626654Z     #0 0x7f1c71a2a805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
2021-12-02T14:05:40.1627846Z     #1 0x7f1c70fe99ee  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x149ee)
2021-12-02T14:05:40.1628431Z 
2021-12-02T14:05:40.1629738Z SUMMARY: AddressSanitizer: heap-buffer-overflow /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:3707 in sqlite3_sharedprefix_fn
2021-12-02T14:05:40.1630900Z Shadow bytes around the buggy address:
2021-12-02T14:05:40.1631528Z   0x0c187ffff820: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
2021-12-02T14:05:40.1632146Z   0x0c187ffff830: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
2021-12-02T14:05:40.1632774Z   0x0c187ffff840: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.1633351Z   0x0c187ffff850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.1633874Z   0x0c187ffff860: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.1634442Z =>0x0c187ffff870: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
2021-12-02T14:05:40.1634966Z   0x0c187ffff880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.1635652Z   0x0c187ffff890: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.1636270Z   0x0c187ffff8a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.1636898Z   0x0c187ffff8b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.1637531Z   0x0c187ffff8c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.1638276Z Shadow byte legend (one shadow byte represents 8 application bytes):
2021-12-02T14:05:40.1638956Z   Addressable:           00
2021-12-02T14:05:40.1639484Z   Partially addressable: 01 02 03 04 05 06 07 
2021-12-02T14:05:40.1640032Z   Heap left redzone:       fa
2021-12-02T14:05:40.1640527Z   Freed heap region:       fd
2021-12-02T14:05:40.1641000Z   Stack left redzone:      f1
2021-12-02T14:05:40.1641480Z   Stack mid redzone:       f2
2021-12-02T14:05:40.1641948Z   Stack right redzone:     f3
2021-12-02T14:05:40.1642433Z   Stack after return:      f5
2021-12-02T14:05:40.1642900Z   Stack use after scope:   f8
2021-12-02T14:05:40.1643457Z   Global redzone:          f9
2021-12-02T14:05:40.1643928Z   Global init order:       f6
2021-12-02T14:05:40.1644383Z   Poisoned by user:        f7
2021-12-02T14:05:40.1644877Z   Container overflow:      fc
2021-12-02T14:05:40.1645374Z   Array cookie:            ac
2021-12-02T14:05:40.1645849Z   Intra object redzone:    bb
2021-12-02T14:05:40.1646318Z   ASan internal:           fe
2021-12-02T14:05:40.1646802Z   Left alloca redzone:     ca
2021-12-02T14:05:40.1647306Z   Right alloca redzone:    cb
2021-12-02T14:05:40.1647757Z   Shadow gap:              cc
2021-12-02T14:05:40.1648353Z ==27529==ABORTING'
2021-12-02T14:05:40.1648726Z ++ err
2021-12-02T14:05:40.1649223Z ++ trap - ERR
2021-12-02T14:05:40.1649640Z ++ echo ERROR REPORTS
2021-12-02T14:05:40.1650087Z ERROR REPORTS
```
```
2021-12-02T14:05:40.1671765Z 
2021-12-02T14:05:40.1672530Z FAIL: run-debuginfod-archive-test.sh
2021-12-02T14:05:40.1673317Z ====================================
2021-12-02T14:05:40.1673582Z 
...
2021-12-02T14:05:40.2554755Z =================================================================
2021-12-02T14:05:40.2555949Z ==27764==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c00002b740 at pc 0x55b4e8f854dd bp 0x7f3508c49ae0 sp 0x7f3508c49ad0
2021-12-02T14:05:40.2557256Z READ of size 1 at 0x60c00002b740 thread T24 (mhd-buildid)
2021-12-02T14:05:40.2558231Z     #0 0x55b4e8f854dc in sqlite3_sharedprefix_fn /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:3707
2021-12-02T14:05:40.2559507Z     #1 0x7f3512ff8d45  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x9bd45)
2021-12-02T14:05:40.2560659Z     #2 0x7f3513002419 in sqlite3_step (/lib/x86_64-linux-gnu/libsqlite3.so.0+0xa5419)
2021-12-02T14:05:40.2561906Z     #3 0x55b4e9083f34 in sqlite_ps::step() /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:977
2021-12-02T14:05:40.2563039Z     #4 0x55b4e8fb7da3 in handle_buildid /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:1916
2021-12-02T14:05:40.2564147Z     #5 0x55b4e8fe5298 in handler_cb /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:2286
2021-12-02T14:05:40.2565391Z     #6 0x7f351308e7e0  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x67e0)
2021-12-02T14:05:40.2566565Z     #7 0x7f3513090837  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x8837)
2021-12-02T14:05:40.2567726Z     #8 0x7f35130928dd  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0xa8dd)
2021-12-02T14:05:40.2568913Z     #9 0x7f3513096068  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0xe068)
2021-12-02T14:05:40.2570106Z     #10 0x7f3512e81608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
2021-12-02T14:05:40.2571376Z     #11 0x7f351223c292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
2021-12-02T14:05:40.2571847Z 
2021-12-02T14:05:40.2572725Z 0x60c00002b740 is located 0 bytes to the right of 128-byte region [0x60c00002b6c0,0x60c00002b740)
2021-12-02T14:05:40.2573676Z allocated by thread T24 (mhd-buildid) here:
2021-12-02T14:05:40.2574668Z     #0 0x7f3513bb0bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
2021-12-02T14:05:40.2575746Z     #1 0x7f3512fa2cfa  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x45cfa)
2021-12-02T14:05:40.2576259Z 
2021-12-02T14:05:40.2576981Z Thread T24 (mhd-buildid) created by T1 (MHD-listen) here:
2021-12-02T14:05:40.2578049Z     #0 0x7f3513add805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
2021-12-02T14:05:40.2579242Z     #1 0x7f351309c9ee  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x149ee)
2021-12-02T14:05:40.2579815Z 
2021-12-02T14:05:40.2580440Z Thread T1 (MHD-listen) created by T0 here:
2021-12-02T14:05:40.2581452Z     #0 0x7f3513add805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
2021-12-02T14:05:40.2582617Z     #1 0x7f351309c9ee  (/lib/x86_64-linux-gnu/libmicrohttpd.so.12+0x149ee)
2021-12-02T14:05:40.2583180Z 
2021-12-02T14:05:40.2584482Z SUMMARY: AddressSanitizer: heap-buffer-overflow /home/runner/work/elfutils/elfutils/debuginfod/debuginfod.cxx:3707 in sqlite3_sharedprefix_fn
2021-12-02T14:05:40.2585651Z Shadow bytes around the buggy address:
2021-12-02T14:05:40.2586265Z   0x0c187fffd690: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
2021-12-02T14:05:40.2586905Z   0x0c187fffd6a0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
2021-12-02T14:05:40.2587535Z   0x0c187fffd6b0: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.2588248Z   0x0c187fffd6c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.2588779Z   0x0c187fffd6d0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.2589359Z =>0x0c187fffd6e0: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
2021-12-02T14:05:40.2589904Z   0x0c187fffd6f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T14:05:40.2590468Z   0x0c187fffd700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.2591102Z   0x0c187fffd710: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.2591720Z   0x0c187fffd720: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.2592343Z   0x0c187fffd730: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
2021-12-02T14:05:40.2593108Z Shadow byte legend (one shadow byte represents 8 application bytes):
2021-12-02T14:05:40.2593768Z   Addressable:           00
2021-12-02T14:05:40.2594306Z   Partially addressable: 01 02 03 04 05 06 07 
2021-12-02T14:05:40.2594912Z   Heap left redzone:       fa
2021-12-02T14:05:40.2595411Z   Freed heap region:       fd
2021-12-02T14:05:40.2595881Z   Stack left redzone:      f1
2021-12-02T14:05:40.2596357Z   Stack mid redzone:       f2
2021-12-02T14:05:40.2596842Z   Stack right redzone:     f3
2021-12-02T14:05:40.2597312Z   Stack after return:      f5
2021-12-02T14:05:40.2597792Z   Stack use after scope:   f8
2021-12-02T14:05:40.2598255Z   Global redzone:          f9
2021-12-02T14:05:40.2598717Z   Global init order:       f6
2021-12-02T14:05:40.2599176Z   Poisoned by user:        f7
2021-12-02T14:05:40.2599668Z   Container overflow:      fc
2021-12-02T14:05:40.2600144Z   Array cookie:            ac
2021-12-02T14:05:40.2600599Z   Intra object redzone:    bb
2021-12-02T14:05:40.2601081Z   ASan internal:           fe
2021-12-02T14:05:40.2601543Z   Left alloca redzone:     ca
2021-12-02T14:05:40.2602033Z   Right alloca redzone:    cb
2021-12-02T14:05:40.2602481Z   Shadow gap:              cc
2021-12-02T14:05:40.2603075Z ==27764==ABORTING'
2021-12-02T14:05:40.2603462Z ++ err
2021-12-02T14:05:40.2603942Z ++ trap - ERR
2021-12-02T14:05:40.2604369Z ++ echo ERROR REPORTS
```

**Comment by evverx** [comment]
Looks like it should be addressed in https://sourceware.org/pipermail/elfutils-devel/2021q4/004426.html
