### ISSUE TITLE
AddressSanitizer: stack-buffer-overflow in n read_long_names with strict_string_checks=1

### ISSUE THREAD

**Issue by evverx** [evverx/elfutils#9]
```
2021-12-02T15:06:28.8429080Z make  check-TESTS
2021-12-02T15:06:29.2606094Z FAIL: run-arextract.sh
2021-12-02T15:06:29.3923558Z FAIL: run-arsymtest.sh
...
2021-12-02T15:15:33.1300016Z FAIL: run-arextract.sh
2021-12-02T15:15:33.1300451Z ======================
2021-12-02T15:15:33.1300675Z 
2021-12-02T15:15:33.1301239Z Extracting symbols... =================================================================
2021-12-02T15:15:33.1302582Z ==18647==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ff29b48965c at pc 0x7ff29f971630 bp 0x7ffce088ed80 sp 0x7ffce088e528
2021-12-02T15:15:33.1303611Z READ of size 13 at 0x7ff29b48965c thread T0
2021-12-02T15:15:33.1304704Z     #0 0x7ff29f97162f  (/lib/x86_64-linux-gnu/libasan.so.5+0x5662f)
2021-12-02T15:15:33.1305699Z     #1 0x7ff29f971d90 in strtol (/lib/x86_64-linux-gnu/libasan.so.5+0x56d90)
2021-12-02T15:15:33.1306348Z     #2 0x7ff29f7bf878 in atol /usr/include/stdlib.h:368
2021-12-02T15:15:33.1307233Z     #3 0x7ff29f7bf878 in read_long_names /home/runner/work/elfutils/elfutils/libelf/elf_begin.c:759
2021-12-02T15:15:33.1308118Z     #4 0x7ff29f7bf878 in __libelf_next_arhdr_wrlock /home/runner/work/elfutils/elfutils/libelf/elf_begin.c:905
2021-12-02T15:15:33.1308973Z     #5 0x7ff29f7c1a29 in elf_next /home/runner/work/elfutils/elfutils/libelf/elf_next.c:63
2021-12-02T15:15:33.1309779Z     #6 0x55854be2e6e4 in main /home/runner/work/elfutils/elfutils/tests/arextract.c:146
2021-12-02T15:15:33.1310919Z     #7 0x7ff29ebbc0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2021-12-02T15:15:33.1312195Z     #8 0x55854be2e40d in _start (/home/runner/work/elfutils/elfutils/tests/arextract+0x240d)
2021-12-02T15:15:33.1312696Z 
2021-12-02T15:15:33.1313185Z Address 0x7ff29b48965c is located in stack of thread T0 at offset 92 in frame
2021-12-02T15:15:33.1314267Z     #0 0x7ff29f7bde16 in __libelf_next_arhdr_wrlock /home/runner/work/elfutils/elfutils/libelf/elf_begin.c:838
2021-12-02T15:15:33.1314809Z 
2021-12-02T15:15:33.1315274Z   This frame has 7 object(s):
2021-12-02T15:15:33.1316179Z     [32, 92) 'hdrm' (line 722) <== Memory access at offset 92 overflows this variable
2021-12-02T15:15:33.1317299Z     [128, 135) 'buf' (line 987)
2021-12-02T15:15:33.1317824Z     [160, 167) 'buf' (line 988)
2021-12-02T15:15:33.1318327Z     [192, 201) 'buf' (line 989)
2021-12-02T15:15:33.1318838Z     [224, 235) 'buf' (line 990)
2021-12-02T15:15:33.1319438Z     [256, 267) 'buf' (line 752)
2021-12-02T15:15:33.1320049Z     [288, 301) 'buf' (line 986)
2021-12-02T15:15:33.1320737Z HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
2021-12-02T15:15:33.1321523Z       (longjmp and C++ exceptions *are* supported)
2021-12-02T15:15:33.1322791Z SUMMARY: AddressSanitizer: stack-buffer-overflow (/lib/x86_64-linux-gnu/libasan.so.5+0x5662f) 
2021-12-02T15:15:33.1323606Z Shadow bytes around the buggy address:
2021-12-02T15:15:33.1324078Z   0x0ffed3689270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1324631Z   0x0ffed3689280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2021-12-02T15:15:33.1325141Z   0x0ffed3689290: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2021-12-02T15:15:33.1325634Z   0x0ffed36892a0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
2021-12-02T15:15:33.1326078Z   0x0ffed36892b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1326527Z =>0x0ffed36892c0: f1 f1 f1 f1 00 00 00 00 00 00 00[04]f2 f2 f2 f2
2021-12-02T15:15:33.1326984Z   0x0ffed36892d0: 07 f2 f2 f2 07 f2 f2 f2 00 01 f2 f2 00 03 f2 f2
2021-12-02T15:15:33.1327450Z   0x0ffed36892e0: 00 03 f2 f2 00 05 f3 f3 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1327890Z   0x0ffed36892f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1328665Z   0x0ffed3689300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1329099Z   0x0ffed3689310: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1329679Z Shadow byte legend (one shadow byte represents 8 application bytes):
2021-12-02T15:15:33.1330248Z   Addressable:           00
2021-12-02T15:15:33.1330708Z   Partially addressable: 01 02 03 04 05 06 07 
2021-12-02T15:15:33.1331270Z   Heap left redzone:       fa
2021-12-02T15:15:33.1331691Z   Freed heap region:       fd
2021-12-02T15:15:33.1332094Z   Stack left redzone:      f1
2021-12-02T15:15:33.1332502Z   Stack mid redzone:       f2
2021-12-02T15:15:33.1332904Z   Stack right redzone:     f3
2021-12-02T15:15:33.1333319Z   Stack after return:      f5
2021-12-02T15:15:33.1333718Z   Stack use after scope:   f8
2021-12-02T15:15:33.1334123Z   Global redzone:          f9
2021-12-02T15:15:33.1334676Z   Global init order:       f6
2021-12-02T15:15:33.1335082Z   Poisoned by user:        f7
2021-12-02T15:15:33.1335617Z   Container overflow:      fc
2021-12-02T15:15:33.1336033Z   Array cookie:            ac
2021-12-02T15:15:33.1336480Z   Intra object redzone:    bb
2021-12-02T15:15:33.1336874Z   ASan internal:           fe
2021-12-02T15:15:33.1337282Z   Left alloca redzone:     ca
2021-12-02T15:15:33.1337706Z   Right alloca redzone:    cb
2021-12-02T15:15:33.1338089Z   Shadow gap:              cc
2021-12-02T15:15:33.1338446Z ==18647==ABORTING
2021-12-02T15:15:33.1339128Z FAIL run-arextract.sh (exit status: 1)
2021-12-02T15:15:33.1339470Z 
2021-12-02T15:15:33.1339967Z FAIL: run-arsymtest.sh
2021-12-02T15:15:33.1340336Z ======================
2021-12-02T15:15:33.1340543Z 
2021-12-02T15:15:33.1340857Z =================================================================
2021-12-02T15:15:33.1341910Z ==18664==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f02096b025c at pc 0x7f020db9c630 bp 0x7ffe10d2a000 sp 0x7ffe10d297a8
2021-12-02T15:15:33.1342779Z READ of size 13 at 0x7f02096b025c thread T0
2021-12-02T15:15:33.1343919Z     #0 0x7f020db9c62f  (/lib/x86_64-linux-gnu/libasan.so.5+0x5662f)
2021-12-02T15:15:33.1344903Z     #1 0x7f020db9cd90 in strtol (/lib/x86_64-linux-gnu/libasan.so.5+0x56d90)
2021-12-02T15:15:33.1345604Z     #2 0x7f020d9ea878 in atol /usr/include/stdlib.h:368
2021-12-02T15:15:33.1346481Z     #3 0x7f020d9ea878 in read_long_names /home/runner/work/elfutils/elfutils/libelf/elf_begin.c:759
2021-12-02T15:15:33.1347442Z     #4 0x7f020d9ea878 in __libelf_next_arhdr_wrlock /home/runner/work/elfutils/elfutils/libelf/elf_begin.c:905
2021-12-02T15:15:33.1348463Z     #5 0x7f020d9ecd78 in elf_rand /home/runner/work/elfutils/elfutils/libelf/elf_rand.c:53
2021-12-02T15:15:33.1349682Z     #6 0x55c73b2a8848 in main /home/runner/work/elfutils/elfutils/tests/arsymtest.c:90
2021-12-02T15:15:33.1350791Z     #7 0x7f020cde70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2021-12-02T15:15:33.1351796Z     #8 0x55c73b2a83ad in _start (/home/runner/work/elfutils/elfutils/tests/arsymtest+0x23ad)
2021-12-02T15:15:33.1352550Z 
2021-12-02T15:15:33.1353179Z Address 0x7f02096b025c is located in stack of thread T0 at offset 92 in frame
2021-12-02T15:15:33.1354110Z     #0 0x7f020d9e8e16 in __libelf_next_arhdr_wrlock /home/runner/work/elfutils/elfutils/libelf/elf_begin.c:838
2021-12-02T15:15:33.1354642Z 
2021-12-02T15:15:33.1355007Z   This frame has 7 object(s):
2021-12-02T15:15:33.1355836Z     [32, 92) 'hdrm' (line 722) <== Memory access at offset 92 overflows this variable
2021-12-02T15:15:33.1356538Z     [128, 135) 'buf' (line 987)
2021-12-02T15:15:33.1357211Z     [160, 167) 'buf' (line 988)
2021-12-02T15:15:33.1357734Z     [192, 201) 'buf' (line 989)
2021-12-02T15:15:33.1358245Z     [224, 235) 'buf' (line 990)
2021-12-02T15:15:33.1358744Z     [256, 267) 'buf' (line 752)
2021-12-02T15:15:33.1359377Z     [288, 301) 'buf' (line 986)
2021-12-02T15:15:33.1360215Z HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
2021-12-02T15:15:33.1361180Z       (longjmp and C++ exceptions *are* supported)
2021-12-02T15:15:33.1362322Z SUMMARY: AddressSanitizer: stack-buffer-overflow (/lib/x86_64-linux-gnu/libasan.so.5+0x5662f) 
2021-12-02T15:15:33.1363125Z Shadow bytes around the buggy address:
2021-12-02T15:15:33.1363608Z   0x0fe0c12cdff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1364230Z   0x0fe0c12ce000: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2021-12-02T15:15:33.1364747Z   0x0fe0c12ce010: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
2021-12-02T15:15:33.1365224Z   0x0fe0c12ce020: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
2021-12-02T15:15:33.1365684Z   0x0fe0c12ce030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1366137Z =>0x0fe0c12ce040: f1 f1 f1 f1 00 00 00 00 00 00 00[04]f2 f2 f2 f2
2021-12-02T15:15:33.1366596Z   0x0fe0c12ce050: 07 f2 f2 f2 07 f2 f2 f2 00 01 f2 f2 00 03 f2 f2
2021-12-02T15:15:33.1367056Z   0x0fe0c12ce060: 00 03 f2 f2 00 05 f3 f3 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1367734Z   0x0fe0c12ce070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1368192Z   0x0fe0c12ce080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1368623Z   0x0fe0c12ce090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2021-12-02T15:15:33.1369208Z Shadow byte legend (one shadow byte represents 8 application bytes):
2021-12-02T15:15:33.1369903Z   Addressable:           00
2021-12-02T15:15:33.1370353Z   Partially addressable: 01 02 03 04 05 06 07 
2021-12-02T15:15:33.1370806Z   Heap left redzone:       fa
2021-12-02T15:15:33.1371222Z   Freed heap region:       fd
2021-12-02T15:15:33.1371622Z   Stack left redzone:      f1
2021-12-02T15:15:33.1372028Z   Stack mid redzone:       f2
2021-12-02T15:15:33.1372425Z   Stack right redzone:     f3
2021-12-02T15:15:33.1372831Z   Stack after return:      f5
2021-12-02T15:15:33.1373343Z   Stack use after scope:   f8
2021-12-02T15:15:33.1373752Z   Global redzone:          f9
2021-12-02T15:15:33.1374141Z   Global init order:       f6
2021-12-02T15:15:33.1374544Z   Poisoned by user:        f7
2021-12-02T15:15:33.1374966Z   Container overflow:      fc
2021-12-02T15:15:33.1375359Z   Array cookie:            ac
2021-12-02T15:15:33.1375761Z   Intra object redzone:    bb
2021-12-02T15:15:33.1376155Z   ASan internal:           fe
2021-12-02T15:15:33.1376564Z   Left alloca redzone:     ca
2021-12-02T15:15:33.1376972Z   Right alloca redzone:    cb
2021-12-02T15:15:33.1377362Z   Shadow gap:              cc
2021-12-02T15:15:33.1377715Z ==18664==ABORTING
2021-12-02T15:15:33.1378375Z FAIL run-arsymtest.sh (exit status: 1)
```

**Comment by evverx** [comment]
It was discussed in https://sourceware.org/pipermail/elfutils-devel/2022q1/004721.html and it was decided that it doesn't make sense to fix it.
